STUDY and SCENARIO DEFINITION -- File TRANUS.CTL
*------------------------------------------------------------------------- /
1.0 STUDY AREA IDENTIFICATION
    'Code'          'Name'                           
    'EXC'           'Example C with land use'        
*------------------------------------------------------------------------- /
2.0 SCENARIOS
    'Code'          'Name'                           'Prev'          
    '03A'           'Base Case'                      ' '
*------------------------------------------------------------------------- /
3.0 Model
3.1 TRANS Use Logit model instead of Powit
    1
3.2 LOC Use Logit model instead of Powit
    1
*------------------------------------------------------------------------- /
